### ISSUE TITLE
Can you provide the download link for your RSNA dataset

### ISSUE THREAD

**Issue by USTCXSC** [jun-sato/AnatMix#1]
Thank you very much for your contribution. I think your work is very meaningful and excellent. I would like to cite your article, but I am currently facing an issue where there is no RSNA dataset available. Can you provide a download connection for the RSNA dataset that you have processed.

**Comment by jun-sato** [comment]
Thank you for having interest in my work.
As shown in my paper, you can have access to the dataset through Kaggle.
https://www.kaggle.com/competitions/rsna-pneumonia-detection-challenge/data

**Comment by USTCXSC** [comment]
Thank you very much for your prompt reply. This dataset is unprocessed and not divided into training, validation, and testing sets. After processing, I found that there is an imbalance between abnormal and normal data in the dataset, which makes it impossible to make a fair comparison with your model. Therefore, we kindly request that you provide the dataset that has been processed by you.

**Comment by jun-sato** [comment]
The competition dataset is not allowed to redistribute to people who don't participate in the competition.
So could you show me that you have participated in the competition through Kaggle plattform?
https://www.kaggle.com/junyasato

I will send you the data using Kaggle.

**Comment by USTCXSC** [comment]
<img width="1021" alt="1716353597216" src="https://github.com/jun-sato/AnatPaste/assets/101544690/2f25398b-1f50-4e91-9a5a-0b123e824060">Yes, I participated in the Kaggle plattform. I was allowed to get the data, thank you very much, I will contact you on Kaggle

**Comment by FudaMingdaXsc** [comment]
<img width="302" alt="1716354092932" src="https://github.com/jun-sato/AnatPaste/assets/101544690/613e14eb-9004-4ac3-bb70-39fce2181ce5">
I'm very sorry, I just followed you on Kaggle, but I haven't become a contributor to Kaggle and I can't send you messages. Can you send me the dataset via email. My email is: fafuxsc1121@163.com . I'm very sorry to trouble you

**Comment by jun-sato** [comment]
I can contact you on Kaggle, so please tell me your username.

**Comment by USTCXSC** [comment]
Thank you very much for your help.My kaggle is https://www.kaggle.com/shimishilei

**Comment by jun-sato** [comment]
I have shared the RSNA dataset file list with you on Kaggle.

**Comment by USTCXSC** [comment]
Thank you very much, I have downloaded the CSV file of the dataset you provided! Thank you very much for your enthusiastic help to me！
